# Generated by Django 5.0.6 on 2024-07-09 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_click_timestamp_alter_url_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
